//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.29 at 04:26:57 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "com.demo.webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package webservice.demo.com;
